-- NOTE: All the data here was generated using the mockaroo.com web service

--
-- Table: users
--

insert into snappers (username, email, password, created_at, updated_at) values ('me', 'my@email.address', 'aVeryStrongPassword', now(), now());

--
-- Table: photos
--

insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Decentralized user-facing process improvement', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'https://robohash.org/liberoimpeditqui.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Innovative full-range analyzer', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'https://robohash.org/consequunturvoluptasaut.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Face to face responsive capacity', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'https://robohash.org/aliquamquisfacere.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Monitored context-sensitive utilisation', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'https://robohash.org/delectusvoluptasharum.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Persistent multi-state project', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://robohash.org/delectusetomnis.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Virtual optimizing website', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'https://robohash.org/doloreillonam.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Mandatory interactive ability', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'https://robohash.org/quasdoloribusnisi.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Sharable foreground software', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'https://robohash.org/consequaturtemporibuseos.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Cross-platform dedicated focus group', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'https://robohash.org/abquidemtotam.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Exclusive transitional access', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'https://robohash.org/doloresrationedicta.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Customer-focused encompassing workforce', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', 'https://robohash.org/blanditiisquiadipisci.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Sharable client-server archive', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'https://robohash.org/velitsuscipiterror.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Implemented background task-force', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'https://robohash.org/rationelaboriosamquis.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Re-contextualized group', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'https://robohash.org/placeatsitillo.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Balanced encompassing alliance', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'https://robohash.org/eosmaximereiciendis.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Fundamental systematic encryption', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'https://robohash.org/suntassumendarepellendus.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Decentralized coherent groupware', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 'https://robohash.org/suntimpeditdolorum.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Compatible holistic process improvement', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'https://robohash.org/corrupticorporissed.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Re-contextualized loyalty', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'https://robohash.org/teneturvoluptatibuseum.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Extended explicit focus group', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'https://robohash.org/atpariaturdolores.png?size=640x320&set=set1', now(), now(), 1);
insert into photos (title, description, url, created_at, updated_at, snapper_id) values ('Inverse fault-tolerant success', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'https://robohash.org/autinventoresoluta.png?size=640x320&set=set1', now(), now(), 1);
